spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javacrud
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:javacrud}
    password: ${POSTGRES_PASSWORD:javacrud}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
